Django/mywebsite/myfirstapp/urls.py
from django.urls import path
from . import views

app_name = "myfirstapp" #Me permite poner urls de forma mas elegante    

urlpatterns = [
    path("", views.index, name="index"),

    # ejemplo: /myfirstapp/5/detalles/
    path("<int:estudiante_id>/detalles/", views.detalles, name="detalles"),

    # ejemplo: /myfirstapp/5/carreras/
    path("<int:estudiante_id>/carreras/", views.carreras, name="carreras"),
    
    # ejemplo: /myfirstapp/5/agrega_carrera/
    path("<int:estudiante_id>/agrega_carrera/", views.agrega_carrera, name="agrega_carrera"),

    path("asincrono/", views.asincrono, name="asincrono"),

]

Django/mywebsite/mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("myfirstapp/", include("myfirstapp.urls")),#dentro de mi directorio raiz hay una aplicacion (correspondencia total)
    #del paquete myfirstapp, agrega los urls de ese paquete
    path("admin/", admin.site.urls),
]

Django/mywebsite/myfirstapp/models.py
from django.db import models

# Create your models here.

class Estudiante(models.Model):
    nombre = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    edad = models.IntegerField(default=0)
    promedio = models.FloatField(default=9.99)
    foraneo = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre + " " + self.apellidos
    
    def aspira_a_beca(self):
        return self.promedio >= 9


class Carrera(models.Model):
    LICENCIATURA = 1
    INGENIERIA = 2
    OPCIONES_TIPO = (
    (LICENCIATURA, "Licenciatura"),
    (INGENIERIA, "Ingenieria"),
    )
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    tipo = models.IntegerField(choices=OPCIONES_TIPO, null=True, blank=True)
    nombre = models.CharField(max_length=200)

    def __str__(self):
        return str(self.tipo) + " " + self.nombre
    
    def get_tipo(self):
        return Carrera.OPCIONES_TIPO[self.tipo-1][1]

Django/mywebsite/myfirstapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests
from .models import Estudiante, Carrera
from django.template import loader
from django.shortcuts import get_object_or_404


# Create your views here.

def index(request):
    return HttpResponse("Hola a todos desde myfirstapp")

def detalles(request, estudiante_id):
    return HttpResponse("Detalles del estudiante %s." % estudiante_id)

def carreras(request, estudiante_id):
    return HttpResponse("Carreras del estudiante %s." % estudiante_id)

def agrega_carrera(request, estudiante_id):
    return HttpResponse("Agregando una carrera a %s." % estudiante_id)

def index(request):
    estudiantes = Estudiante.objects.order_by("nombre")
    context = {
    "estudiantes": estudiantes,
    }
    return render(request, "myfirstapp/index.html", context)

def detalles(request, estudiante_id):
    estudiante = get_object_or_404(Estudiante, pk=estudiante_id)
    return render(request, "myfirstapp/detalles.html", 
    {"estudiante": estudiante})

async def asincrono(request):
    url = "https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0"
    respuesta = requests.get(url)
    print("-------------------",respuesta)
    print(respuesta.json()) 
    return HttpResponse("Respuesta asincrona %s." % respuesta.json())

# async def asincrono(requeest):
#     print("hola")
#     return HttpResponse("Respuesta: hola")

Django/mywebsite/myfirstapp/templates/myfirstapp/detalles.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Detalles</title>
    </head>
    <body>
        <p> Información del Estudiante </p>
        {% if estudiante %}
            <p>{{ estudiante.id }} </p>
            <p>{{ estudiante.nombre }} 
            <p>{{ estudiante.apellidos }} </p>
            <p>{{ estudiante.promedio }} </p>
            {% if estudiante.foraneo %}
                <p>Foráneo</p>
            {% else %}
                <p>Local </p>
            {% endif %} 

            <ul>
            {% for carrera in estudiante.carrera_set.all %}
                <li> {{ carrera.get_tipo }} {{ carrera.nombre }} </li>
            {% endfor %}
            </ul>
        {% endif %} 
    </body>
</html>

Django/mywebsite/myfirstapp/templates/myfirstapp/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Index page</title>
    </head>
    <body>
        {% load static %}
        <script src="{% static 'myfirstapp/myjavascript.js' %}"></script>

        <p>Listado de estudiantes</p>
        {% if estudiantes %}
        <ul>
        {% for estudiante in estudiantes %}
            <li><a href="{% url 'myfirstapp:detalles' estudiante.id %}">>
                    {{estudiante.nombre}} 
                    {{estudiante.apellidos}} 
                </a></li>
        {% endfor %}
        </ul>
        {% else %}
            <p>No hay estudiantes registrados.</p>
        {% endif %}

        <input type="button" value="Prueba" onclick="hola();">
    </body>
</html>